### ISSUE TITLE
TEDLUIM

### ISSUE THREAD

**Issue by rajivpoddar** [samsungsds-rnd/deepspeech.mxnet#1]
Any plans to add support for the TEDLUIM dataset? It would be good to benchmark it against other DeepSpeech2 implementations, eg. [Mozilla DeepSpeech](https://github.com/mozilla/DeepSpeech) and [PyTorch DeepSpeech](https://github.com/SeanNaren/deepspeech.pytorch).

**Comment by Soonhwan-Kwon** [comment]
Thank you for your suggestion, and I'm middle of downloading the dataset. 
We will add more support for other dataset like TEDLIUM after we provide the decent model template for LibriSpeech.

**Comment by rajivpoddar** [comment]
Thanks for looking into it! TEDLIUM is more of a natural speech dataset. It would be interesting to compare it with LibriSpeech which is dictated speech.

Are you also using a language model?

**Comment by Soonhwan-Kwon** [comment]
No, in this example we don't use any language model for decoding.
