### ISSUE TITLE
Does it have cpu support, only gpu?

### ISSUE THREAD

**Issue by lionel92** [samsungsds-rnd/deepspeech.mxnet#16]
As the environments shows GPU memory size requirement and the .cfg file only has the option :
#ex: gpu0,gpu1,gpu2,gpu3
context = gpu0
I want to make sure if the program only support GPU mode.

**Comment by Soonhwan-Kwon** [comment]
It supports cpu as well, but it will takes too long to train, so I don’t recommend. context = cpu0 will take effect.
