### ISSUE TITLE
hard to understand the gru implementation, could you explain?

### ISSUE THREAD

**Issue by phoenixbai** [samsungsds-rnd/deepspeech.mxnet#19]
hi, 
me again. I have a question regarding to the implementation of gru.
how your implementation is equal to formulas below? I have a hard time understanding the equivalence of these two. Could you help enlighten me? 
<img width="521" alt="screen shot 2018-06-11 at 11 32 33 am" src="https://user-images.githubusercontent.com/1182565/41216247-135df1a6-6d86-11e8-9937-e35787a8cb58.png">

**Comment by rongzha1** [comment]
pls refer closed issue :    GRU implementation #13

**Comment by Soonhwan-Kwon** [comment]
Thank you for reference @rongzha1
