### ISSUE TITLE
Will this branch merge into master branch?

### ISSUE THREAD

**Issue by ysh329** [samsungsds-rnd/deepspeech.mxnet#2]
Thanks in advance! :laughing:

**Comment by Soonhwan-Kwon** [comment]
for now it is working code, but I'm middle of testing to improve speed of  sample normalization function.

**Comment by Soonhwan-Kwon** [comment]
@ysh329 I pulled request to dmlc mxnet and finished the test. And there was a bug in baidu's flac_to_wav.sh script, so I uploaded fixed flac_to_wav.sh on our repository. Please read README.md.

**Comment by ysh329** [comment]
@Soonhwan-Kwon Nice work :+1:
