### ISSUE TITLE
How do I use dropout?

### ISSUE THREAD

**Issue by fanlu** [samsungsds-rnd/deepspeech.mxnet#4]
I found that there are several places where you can dropout, what experience do you have?

**Comment by Soonhwan-Kwon** [comment]
In deep speech 2 paper, they didn't use dropout but if many users want it's not need much work because we already using drop out in other project.

**Comment by fanlu** [comment]
Do you know what other regularized skills they use?

**Comment by Soonhwan-Kwon** [comment]
I assume that batch normalization can do regularization. please see this paper's section 3.4 https://arxiv.org/pdf/1502.03167.pdf
