### ISSUE TITLE
about contrib.sym.ctc_loss?

### ISSUE THREAD

**Issue by BackT0TheFuture** [samsungsds-rnd/deepspeech.mxnet#7]
Hi,there
how to change warpctc with mx.contrib.sym.ctc_loss?
thx!

**Comment by Soonhwan-Kwon** [comment]
Okay I expect it easy and will try to update it today or tomorrow

**Comment by Soonhwan-Kwon** [comment]
I tried to make change to mx.contrib.sym.ctc_loss but I found that there is an issue for performance now.
Please see https://github.com/apache/incubator-mxnet/issues/7154.
As far as I know baidu's warpctc has gpu mode, so cpu mode for ctc_loss is inappropriate.
Meanwhile, I expect external warpctc is safe to use.

**Comment by BackT0TheFuture** [comment]
got it !  
thanks !

**Comment by fanlu** [comment]
apache/incubator-mxnet#7442
Dose this not work？

**Comment by Soonhwan-Kwon** [comment]
It seems that there is a problem still.
Please refer below link
https://github.com/apache/incubator-mxnet/issues/7445.
And it seems cpu version and cudnn7 version can not be equal implementation,
and they plans to turn cudnn CTC off because of the API design.
@fanlu

**Comment by fanlu** [comment]
It looks like a problem.But how do you deal with problems of mx.sym.Group([softmax_loss, ctc_loss]) and STTMetric? @Soonhwan-Kwon
